### ISSUE TITLE
Files in sub-directories added to root as well

### ISSUE THREAD

**Issue by jakauppila** [bitgenics/deterministic-zip#2]
I was testing this out on Windows and it appears as though files contained within sub-directories of the target folder are getting added at the root as well.

```javascript
const zip = require('deterministic-zip');

zip('H:\\Working\\CodeArchive\\', 'codedeploy.zip', {includes: ['./**'], cwd: 'H:\\Working\\CodeArchive\\'}, (err) => {
    console.log('Done!');
});
```

The source directory looks like this:
**H:\Working\CodeArchive**
```
.
+-- HelloWorld.txt
+-- AnotherFolder
|   +-- GoodByeWorld.txt
```

The resulting zip looks like this:
```
.
+-- HelloWorld.txt
+-- GoodByeWorld.txt
+-- AnotherFolder
|   +-- GoodByeWorld.txt
```

Not sure if this is a bug related to windows, or possibly I'm not specifying the correct options.

**Comment by jakauppila** [comment]
Disregard, just user error.

Apparently there's a `Flat View` setting in 7zip that I had configured and I didn't see the `Path Prefix`

![image](https://user-images.githubusercontent.com/4100127/34579223-b5dd0d6e-f14d-11e7-94c9-c856ff33f64b.png)

**Comment by evanderkoogh** [comment]
Hey @jakauppila. Thanks for investigating and I am glad it is this  😄. I was not looking forward to debugging something this obscure on an OS I don't own.

Let me know if you have any other issues.
